[custom.all.ilex-fasta]
type = "local"
path = "fasta"
ipkg = "ilex-fasta.ipkg"
test = "test/test.ipkg"

[custom.all]
array.commit        = "latest:main"
ilex-core.commit    = "latest:main"
ilex.commit         = "latest:main"
ilex-streams.commit = "latest:main"
